### ISSUE TITLE
From @Greyghay2 on twitter...

### ISSUE THREAD

**Issue by soulp1** [oberocks/vainglory-base-stats#30]
* max damage reduction of cp lance is 90% from gythian wall
  * wp skye’s max A slow
  * Gwen’s A max slow
  * Alpha’s ult least reboot time
  * Tony’s max trash talk duration
  * Baron’s jump jets lowest delay time

**Comment by oberocks** [comment]
Currently these issues pertain to the vainglory tools web site build, and not the data itself. These issues are being kept here as a reminder to update the site and then delete these issues from here. Sorry for any confusion!

**Comment by oberocks** [comment]
everything here has been checked and with gwen's new missing bullet added, these issues are all closed.
